
language: node_js
node_js:
  - "stable"
before_script:
 
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"